#!/bin/sh
# vercel-build.sh
#
# Runs as the Vercel build command (set in vercel.json).
# Reads environment variables set in the Vercel dashboard and
# writes them into src/js/config.js before the static files are served.
#
# Required environment variables (set in Vercel → Settings → Environment Variables):
#   VITE_CONTRACT_ADDRESS  — deployed contract address (0x…)
#   VITE_NETWORK_ID        — chain ID as integer (e.g. 11155111 for Sepolia)

set -e

cat > src/js/config.js <<EOF
/**
 * src/js/config.js — generated by vercel-build.sh
 * Do not edit manually.
 */

const CONTRACT_ADDRESS = '${VITE_CONTRACT_ADDRESS}';
const NETWORK_ID       = ${VITE_NETWORK_ID};
EOF

echo "config.js written:"
cat src/js/config.js
