/**
 * src/js/config.js
 *
 * Runtime configuration — generated by vercel-build.sh at deploy time
 * from Vercel environment variables. Do not commit this file.
 *
 * For local development: copy config.example.js to config.js
 * and fill in your values manually.
 */

const CONTRACT_ADDRESS = '0x9fde45c4Cf5bdfC6FE1e072932DdB00CC1408A1D';
const NETWORK_ID       = 11155111; // Sepolia
